variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - dependencies
  - build
  - package
  - pages

cache:
  paths:
    - .apt
    - gmp-6.1.2.tar.lz

image: registry.plmlab.math.cnrs.fr/neonatool/adftool-builder:latest

before_script:
  - rm -f /etc/apt/apt.conf.d/docker-clean
  - sed "s|@ABS_TOP_SRCDIR@|$PWD|g" gitlab-ci-apt-cache.conf > /etc/apt/apt.conf.d/gitlab-ci-cache
  - mkdir -p .apt/archives/partial
  - apt-get update -y
  - apt-get install -y git
  - git config --global --add safe.directory $PWD

dist:
  stage: dependencies
  script:
    - apt-get install -y git gettext libgmp-dev libhdf5-dev zlib1g-dev autoconf autoconf-archive automake libtool valgrind tar global autopoint make gcc m4 libtinfo5 flex r-base texinfo texlive libpython3-dev pkg-config
    - mkdir -p public
    - export GNULIB_SRCDIR=$PWD/gnulib
    - ./bootstrap --force --skip-po
    - "ls po/*.po | sed 's|.*/||; s|\\.po$||' > po/LINGUAS"
    - mkdir -p build-dist
    - cd build-dist
    - ../configure CPPFLAGS=-I/usr/include/hdf5/serial LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial
    - make -j
    - mv src/libadftool/libadftool_la-lexer.c ../src/libadftool/
    - make -j distcheck DISTCHECK_CONFIGURE_FLAGS="CPPFLAGS=-I/usr/include/hdf5/serial LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial"
    - cp adftool-*.tar.gz ../public/adftool-latest.tar.gz
    - cp ../.version ../public
  artifacts:
    paths:
      - public

build_mingw:
  stage: build
  script:
    - apt-get install -y tar make binutils-mingw-w64-x86-64 gcc-mingw-w64-x86-64 wine
    - tar xf public/adftool-latest.tar.gz
    - mkdir -p build-mingw
    - cd build-mingw
    - ../adftool-*/configure CPPFLAGS=-I/export/mingw64/include 'CFLAGS=-g3 -O2 -DFORTIFY_SOURCE=2 -Wall -Wextra' LIBS=-lhdf5 LDFLAGS=-L/export/mingw64/lib --enable-relocatable --host=x86_64-w64-mingw32 --prefix=/mingw64 --disable-python
    - make -j
    - make -j DESTDIR=$PWD/../public install
    - cp /export/mingw64/bin/*.dll $PWD/../public/mingw64/bin
    - cp -R /export/mingw64/include/* $PWD/../public/mingw64/include/
    - cp -R /export/mingw64/lib/* $PWD/../public/mingw64/lib/
    - cp /export/mingw64/bin/*.dll .
    - make -j check 'LOG_COMPILER = ./libtool --mode=execute wine' 'XFAIL_TESTS = eeg_metadata_example.exe'
    - LANG=fr_FR.UTF-8 wine ../public/mingw64/bin/adftool --aidez-moi
  artifacts:
    paths:
      - public

build_emscripten:
  stage: build
  script:
    - "source /etc/profile || true"
    - apt-get install -y git python3 gettext autoconf autoconf-archive automake libtool valgrind tar autopoint make gcc m4 libtinfo5 lbzip2
    - tar xf public/adftool-latest.tar.gz
    - mkdir -p build-emscripten
    - cd build-emscripten
    - emconfigure ../adftool-*/configure CPPFLAGS=-I/export/emscripten/include LIBS=/export/emscripten/lib/libhdf5.a LDFLAGS=-L/export/emscripten/lib --disable-relocatable --disable-shared --prefix=/emscripten --disable-python --enable-node=yes
    - emmake make -j
    - emmake make -j DESTDIR=$PWD/../public install
    - cp -R /export/emscripten/include/* $PWD/../public/emscripten/include/
    - cp -R /export/emscripten/lib/* $PWD/../public/emscripten/lib/
  artifacts:
    paths:
      - public

build_html:
  stage: build
  script:
    - apt-get install -y gettext libgmp-dev libhdf5-dev zlib1g-dev valgrind tar make gcc libtinfo5 libmpfr-dev texinfo python3 libpython3-dev pkg-config
    - tar xf public/adftool-latest.tar.gz
    - mkdir -p build-html
    - cd build-html
    - ../adftool-*/configure CPPFLAGS=-I/usr/include/hdf5/serial LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial --prefix=/ --htmldir=/adftool
    - make -j
    - make -j html
    - make -j DESTDIR=$PWD/../public install-html
  artifacts:
    paths:
      - public

build_pdf:
  stage: build
  script:
    - apt-get install -y gettext libgmp-dev libhdf5-dev zlib1g-dev valgrind tar make gcc libtinfo5 libmpfr-dev texinfo texlive python3 libpython3-dev pkg-config
    - tar xf public/adftool-latest.tar.gz
    - mkdir -p build-pdf
    - cd build-pdf
    - ../adftool-*/configure CPPFLAGS=-I/usr/include/hdf5/serial LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial --prefix=/ --pdfdir=/
    - make -j
    - make -j pdf
    - make -j DESTDIR=$PWD/../public install-pdf
  artifacts:
    paths:
      - public

conan:
  stage: package
  script:
    - apt-get install -y python3 python3-pip autoconf autoconf-archive automake libtool pkg-config
    - pip3 install conan
    - tar xf public/adftool-latest.tar.gz
    - mkdir conan-build
    - cd conan-build
    - conan remote add gitlab ${CI_API_V4_URL}/projects/$CI_PROJECT_ID/packages/conan
    - conan create ../adftool-* ${CI_PROJECT_NAMESPACE}+${CI_PROJECT_NAME}/latest --build missing -c tools.system.package_manager:mode=install
    - CONAN_LOGIN_USERNAME=${GITLAB_USER_NAME} CONAN_PASSWORD=${CI_JOB_TOKEN} conan upload adftool/$(cat ../adftool-*/.tarball-version)@${CI_PROJECT_NAMESPACE}+${CI_PROJECT_NAME}/latest --all --remote=gitlab

check_npm:
  stage: package
  image: node:14
  script:
    - cp -R public/emscripten/share/nodejs/adftool adftool
    - cd adftool
    - sed -i "s/\"adftool\"/\"@${CI_PROJECT_NAMESPACE}\\/${CI_PROJECT_NAME}\"/g" package.json
    - echo "@${CI_PROJECT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - sed -i 's|^https://|//|g' .npmrc
    - npm install
    - npm run test

publish_npm:
  stage: package
  image: node:14
  script:
    - cp -R public/emscripten/share/nodejs/adftool adftool
    - cd adftool
    - sed -i "s/\"adftool\"/\"@${CI_PROJECT_NAMESPACE}\\/${CI_PROJECT_NAME}\"/g" package.json
    - echo "@${CI_PROJECT_NAMESPACE}:registry=${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/" > .npmrc
    - echo "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> .npmrc
    - sed -i 's|^https://|//|g' .npmrc
    - npm install
    - npm run test
    - npm publish
  only:
    - /^v[0-9]+.[0-9]+.[0-9]+$/

pages:
  stage: pages
  script:
    - echo "nothing to do"
  artifacts:
    paths:
      - public