variables:
  GIT_SUBMODULE_STRATEGY: recursive

pages:
  script:
    - apt-get update -y
    - apt-get install -y git python gettext libhdf5-dev zlib1g-dev autoconf autoconf-archive automake libtool valgrind tar global autopoint make gcc g++ cmake m4 libtinfo5 binutils-mingw-w64-x86-64 g++-mingw-w64 gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 wine flex
    - export GNULIB_SRCDIR=$PWD/gnulib
    - ./bootstrap --force --skip-po
    - mkdir -p build-adftool-mingw64
    - cd build-adftool-mingw64
    - "../configure CPPFLAGS=-I$PWD/../public/mingw64/include LIBS=-lhdf5 LDFLAGS=-L$PWD/../public/mingw64/lib --prefix=$PWD/../public/mingw64 --enable-relocatable --host=x86_64-w64-mingw32 || (cat config.log ; exit 1) || exit 1"
    - make -j
    - make bplus_tree_grow_file_example.exe
    - wine bplus_tree_grow_file_example.exe
    - make -j install
    - cd ..
    - git clone https://github.com/emscripten-core/emsdk.git
    - cd emsdk
    - ./emsdk install latest
    - ./emsdk activate latest
    - source ./emsdk_env.sh
    - cd ..
    - mkdir build-hdf5-with-node build-hdf5-emscripten
    - cd hdf5
    - ln -s /usr/bin/libtoolize ./libtoolize
    - cp src/H5make_libsettings.c src/H5make_libsettings-original.c
    - "(echo '#define main true_main' ; cat src/H5make_libsettings.c ../H5make_libsettings_true_main.c) > src/H5make_libsettings.c-stdin"
    - cp src/H5make_libsettings.c-stdin src/H5make_libsettings.c
    - export HDF5_ACLOCAL=$(which aclocal) ; export HDF5_AUTOHEADER=$(which autoheader) ; export HDF5_AUTOMAKE=$(which automake) ; export HDF5_AUTOCONF=$(which autoconf) ; export HDF5_LIBTOOL=$(which libtool) ; export HDF5_M4=$(which m4) ; ./autogen.sh
    - cd ../build-hdf5-with-node
    - emconfigure ../hdf5/configure --enable-build-mode=production CFLAGS="-std=gnu11" LIBS="-lnodefs.js" --disable-tools --disable-tests
    - emmake make -k -j 8 || true
    - cd src
    - "cat libhdf5.settings | node ./H5make_libsettings > ../../hdf5/src/H5lib_settings.c-emscripten"
    - node ./H5detect > ../../hdf5/src/H5Tinit.c-emscripten
    - cd ../../hdf5
    - cp src/H5make_libsettings-original.c src/H5make_libsettings.c
    - cd ../build-hdf5-emscripten
    - emconfigure ../hdf5/configure --enable-build-mode=production --prefix=$PWD/../public/emscripten --disable-tools --disable-tests
    - emmake make -j 8 -k || true
    - cp ../hdf5/src/H5lib_settings.c-emscripten ../hdf5/src/H5lib_settings.c
    - cp ../hdf5/src/H5Tinit.c-emscripten ../hdf5/src/H5Tinit.c
    - emmake make -j 8
    - emmake make install
    - cd ..
    - mkdir -p build-adftool-native build-adftool-emscripten
    - cd build-adftool-native
    - ../configure CPPFLAGS=-I/usr/include/hdf5/serial LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial
    - make -j
    - make -j check
    - make -j distcheck DISTCHECK_CONFIGURE_FLAGS="CPPFLAGS=-I/usr/include/hdf5/serial LDFLAGS=-L/usr/lib/x86_64-linux-gnu/hdf5/serial"
    - cp adftool-*.tar.gz ../public/adftool-latest.tar.gz
    - cd ../build-adftool-emscripten
    - emconfigure ../configure CPPFLAGS=-I$PWD/../public/emscripten/include LIBS=$PWD/../public/emscripten/lib/libhdf5.a --prefix=$PWD/../public/emscripten --enable-relocatable
    - emmake make -j
    - emmake make install
    - ./libtool --tag=CC --mode=link emcc -O3 libadftool.la -o index.html
    - ls -R .libs
    - cp -R .libs/ ../public
  artifacts:
    paths:
      - public