#!/bin/sh

me="$0"
medir=`dirname "$me"`

if test -z "$GNULIB_SRCDIR"
then
    export GNULIB_SRCDIR="$PWD/gnulib"
fi

cp /usr/share/gettext/gettext.h src/gettext.h

cp "$GNULIB_SRCDIR"/top/* "$medir" && "$medir"/bootstrap "$@"
