name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
    - name: install-dependencies
      run: sudo apt-get install -y git gettext libgmp-dev libhdf5-dev zlib1g-dev autoconf autoconf-archive automake libtool valgrind tar lzip global autopoint make gcc m4 libtinfo5 flex r-base texinfo texlive libpython3-dev pkg-config emacs check r-base r-cran-rcpp
    - name: install-emsdk
      run: git clone --depth 1 https://github.com/emscripten-core/emsdk.git && cd emsdk && ./emsdk install latest && ./emsdk activate latest && cd ..
    - name: build-hdf5-emscrpiten
      run: ./build-hdf5
    - name: build-gmp-emscrpiten
      run: ./build-gmp
    - name: build-check-emscrpiten
      run: ./build-libcheck
    - name: bootstrap
      run: ./bootstrap-bootstrap
    - name: configure
      run: mkdir -p build-adftool-emscripten && cd build-adftool-emscripten && ../configure 
    - name: make
      run: cd build-adftool-emscripten && make -j 8
    - name: make check
      run: cd build-adftool-emscripten && make check -j 8
    - name: make distcheck
      run: cd build-adftool-emscripten && make distcheck -j 8
    - name: emscripten-build
      run: ./build-adftool
    - name: Emscripten compiled code
      uses: actions/upload-artifact@v3
      with:
        name: emscripten-compiled-code
        path: public